language: python
python:
  - "2.7"
cache: pip

script:
  - python pytest.py

notifications: # set notification options
  email:
    recipients:
      - saroup@microsoft.com

    # change is when the repo status goes from pass to fail or vice versa
    on_success: never
    on_failure: change
